- name: Distributing init kojira user
  template:
    src: kojira/kojira-pgsql-rights.sql.j2
    dest: /etc/kojira/kojira-pgsql-rights.sql
    mode: 0644
  register: kojira_user_sql
  tags:
    - kojira

- name: Creating default kojira user in DB
  postgresql_db:
    name: "{{ koji_db_name }}"
    target: /etc/kojira/kojira-pgsql-rights.sql
    state: restore
  become_user: postgres
  when: kojira_user_sql is changed
  tags:
    - kojira

- name: Ensuring we have kojira tls pem for auth
  copy:
    src: "{{ pkistore }}/koji/{{ koji_kojira_tls_pem }}"
    dest: "/etc/pki/koji/{{ koji_kojira_tls_pem}}"
    mode: 0644

- name: Distributing kojira conf file
  template:
    src: kojira/kojira.conf.j2
    dest: /etc/kojira/kojira.conf
    mode: 0644
  notify:
    - restart_kojira

- name: Service kojira is running
  service:
    name: kojira
    state: started
    enabled: yes


