- name: Creating local koji admin user if needed
  user:
    name: "{{ koji_admin_user }}"
    comment: "Local koji admin"

- name: Creating dir for koji config
  file:
    path: "/home/{{ koji_admin_user}}/.koji"
    state: directory
    owner: "{{ koji_admin_user }}"

- name: Configuring koji client for admin
  template:
    src: koji-client-config.j2
    dest: "/home/{{ koji_admin_user}}/.koji/config"
    owner: "{{ koji_admin_user }}"
    
- name: Copy TLS pem files for koji admin user
  copy:
    src: "{{ pkistore }}/koji/{{ koji_admin_pem }}"
    dest: "/etc/pki/koji/{{ koji_admin_pem }}"
    owner: "{{ koji_admin_user }}"
    mode: 0644
  when: koji_auth_tls

- name: Copy keytab for koji admin user
  copy: 
    src: "{{ pkistore }}/koji/{{ koji_admin_keytab }}"
    dest: "/home/{{ koji_admin_user }}/{{ koji_admin_keytab }}"
    owner: "{{ koji_admin_user }}"
    mode: 0644
  when: koji_auth_kerberos
  
- name: Ensuring we have scripts directory
  file:
    path : /opt/cbs-tools/scripts
    state: directory
    mode: 0750
    owner: "{{ koji_admin_user }}"

- name: Importing all needed scripts
  template:
    src: "cbs-tools/scripts/{{ item }}"
    dest: /opt/cbs-tools/scripts/
    owner: "{{ koji_admin_user }}"
    mode: 0750
  with_items:
    - check_tag_perm.py
    - common6.sh
    - common7.sh
    - create_sig.sh
    - external_repos_updates.sh
    - fas_perms_to_koji.py
    - koji-group-sync.py
    - fasjson-group-sync
    - mash_run.sh
    - regen_all_buildroots.sh
    - cbs-fas-sync.sh
    - regen_build_repos.sh
  tags:
    - cbs-tools

- name: Importing SIG config files
  copy:
    src: "cbs_configs/sigs/"
    dest: /opt/cbs-tools/scripts/sigs/
    owner: "{{ koji_admin_user }}"
  when: koji_cbs_sigs_config  
  tags:
    - cbs-tools

- name: Cron job to rebuild repos every day
  cron:
    name: "CentOS Koji regen repo task"
    job: "/opt/cbs-tools/scripts/regen_build_repos.sh > /dev/null 2>&1"
    minute: "5"
    hour: "3"
    user: "{{ koji_admin_user }}"

