- name: Importing specific distro variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags:
    - vars

- ansible.builtin.include_role:
    name: httpd
  vars:
    - httpd_tls: True

- name: Add the kojihub repo if needed
  ansible.builtin.template:
    src: kojihub.repo.j2
    dest: /etc/yum.repos.d/kojihub.repo
    mode: 0644
  when: kojid_kojihub_repo
  tags:
    - repo

- name: Adding repo gpg key if needed
  copy: 
    src: "files/{{ kojid_kojihub_repo_gpgkey }}"
    dest: "/etc/pki/rpm-gpg/{{ kojid_kojihub_repo_gpgkey }}"
  when: kojid_kojihub_repo and kojid_kojihub_repo_gpgcheck  
  tags:
    - repo

- name: Ensuring we have some pkgs installed
  ansible.builtin.yum:
    name: "{{ kojihub_pkgs }}"
    state: installed
    update_cache: True
  tags:
    - pkgs
  notify:
    - restart_httpd

- include_tasks: storage.yml
  tags:
    - storage
    - pruning
    - nfs

- include_tasks: tls.yml
  tags:
    - tls
    - pki

- include_tasks: postgresql.yml
  tags:
    - db

- include_tasks: selinux.yml

- name: Configuring kojihub/web
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    mode: 0644
  with_items:
    - koji-hub/hub.conf
    - kojiweb/web.conf
  notify:
    - restart_httpd
  tags:
    - conf
    - plugins

- name: Configuring robots.txt
  copy:
    src: robots.txt
    dest: /var/www/common/robots.txt
  tags:
    - conf
    - robots

- name: Configuring koji policy
  copy:
    src: "{{ filestore }}/koji/{{ kojihub_policy_filename }}"
    dest: "/etc/koji-hub/hub.conf.d/policy.conf"
    mode: 0644
  when: kojihub_policy_file
  tags:
    - conf
    - policy
  notify:
    - restart_httpd

- name: Deploying koji custom theme
  ansible.builtin.unarchive:
    src: "{{ koji_theme_file }}"
    dest: /
  when:
    - koji_custom_theme
  tags:
    - theme

- name: Configuring httpd for kojihub/web
  ansible.builtin.template:
    src: "httpd/{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
    mode: 0644
  with_items:
    - ssl-koji.conf
    - kojihub.conf
    - kojiweb.conf
  notify:
    - restart_httpd
  tags:
    - httpd_config

- block:
    - name: Importing kojihub keytab
      copy:
        src: "{{ pkistore }}/koji/{{ koji_auth_keytab }}"
        dest: "/etc/koji-hub/{{ koji_auth_keytab }}"
      notify: restart_httpd

    - name: Importing koji-web keytab
      copy:
        src: "{{ pkistore }}/koji/{{ koji_auth_webkeytab }}"
        dest: "/etc/kojiweb/{{ koji_auth_webkeytab }}"
      notify: restart_httpd 
    
  when: koji_auth_kerberos

- ansible.builtin.include_role:
     name: krb5-client
  when: koji_auth_gssapi_localname

- include_tasks: koji-admin.yml
  when: koji_admin_client
  tags:
    - cbs-tools

- include_tasks : plugins.yml
  tags:
    - plugins

- include_tasks: kojira.yml
  when: koji_kojira
  tags:
    - kojira

- include_tasks: mash.yml
  when: koji_mash

- include_tasks: users-sync.yml
  when: koji_fas_sync or koji_fasjson_sync
 
- include_tasks: monitoring.yml 
  tags:
    - monitoring

- include_tasks: koji-gc.yml
  when: kojihub_gc_enabled
  tags:
    - koji-gc
