- include_role:
    name: httpd
  vars:
    - httpd_tls: True

- name: Add the kojihub repo if needed
  template:
    src: kojihub.repo.j2
    dest: /etc/yum.repos.d/kojihub.repo
  when: kojid_kojihub_repo
  tags:
    - repo

- name: Adding repo gpg key if needed
  copy: 
    src: "files/{{ kojid_kojihub_repo_gpgkey }}"
    dest: "/etc/pki/rpm-gpg/{{ kojid_kojihub_repo_gpgkey }}"
  when: kojid_kojihub_repo and kojid_kojihub_repo_gpgcheck  
  tags:
    - repo


- name: Ensuring we have some pkgs installed
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - koji
    - koji-hub
    - koji-hub-plugins
    - koji-web
    - koji-utils
    - git
    - gnupg2
    - repoview

- include_tasks: storage.yml
- include_tasks: tls.yml
- include_tasks: postgresql.yml
- include_tasks: selinux.yml

- name: Configuring kojihub/web
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
  with_items:
    - koji-hub/hub.conf
    - kojiweb/web.conf
  notify:
    - restart_httpd

- name: Deploying koji custom theme
  unarchive:
    src: "{{ koji_theme_file }}"
    dest: /
  when:
    - koji_custom_theme

- name: Configuring httpd for kojihub/web
  template:
    src: "httpd/{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
  with_items:
    - ssl-koji.conf
    - kojihub.conf
    - kojiweb.conf
  notify:
    - restart_httpd


- include_tasks: koji-admin.yml
  when: koji_admin_client

- include_tasks: kojira.yml
  when: koji_kojira
- include_tasks: mash.yml
  when: koji_mash
- include_tasks: users-sync.yml
  when: koji_fas_sync
- include_tasks: monitoring.yml  
