- name: Ensuring we have mash installed
  yum:
    name: mash
    state: latest

- name: Ensuring we have correct rights on some mash directories
  file:
    path: "{{ item }}"
    owner: "{{ koji_admin_user }}"
    state: directory
    mode: 0755
  with_items:
    - /etc/mash
    - /var/log/mash
    - /var/tmp/mash
    - /var/cache/cbs-mash

- name: Configuring mash
  template:
    src: mash/mash.conf.j2
    dest: /etc/mash/mash.conf
    owner: "{{ koji_admin_user }}"
