- block:
    - name: Configuring agent in Zabbix server
      include_role:
        name: zabbix-server
        tasks_from: agent_config
      vars:
        zabbix_templates: "{{ kojihub_zabbix_templates }}"
        zabbix_groups: "{{ kojihub_zabbix_groups }}"
  delegate_to: "{{ zabbix_api_srv }}"  
  tags:
    - monitoring
  when: zabbix_api_srv is defined

- name: Specific local koji monitoring checks
  template:
    src: kojihub-monitoring-checks.j2
    dest: /usr/lib/zabbix/kojihub-monitoring-checks
    mode: 0755
  tags:
    - monitoring

- name: monitoring cron job
  cron:
    name: koji zabbix checks
    job: /usr/lib/zabbix/kojihub-monitoring-checks
    minute: "*/2"
  tags:
    - monitoring
