- block:
    - name: Configuring agent in Zabbix server
      ansible.builtin.include_role:
        name: zabbix-server
        tasks_from: agent_config
      vars:
        zabbix_templates: "{{ kojihub_zabbix_templates }}"
        zabbix_groups: "{{ kojihub_zabbix_groups }}"
  delegate_to: "{{ zabbix_api_srv }}"  
  tags:
    - monitoring
  when: 
    - zabbix_api_srv is defined
    - zabbix_monitoring

- name: Specific local koji monitoring checks
  ansible.builtin.template:
    src: kojihub-monitoring-checks.j2
    dest: /usr/lib/zabbix/kojihub-monitoring-checks
    mode: 0755
  tags:
    - monitoring
  when: 
    - zabbix_api_srv is defined
    - zabbix_monitoring


- name: monitoring cron job
  ansible.builtin.cron:
    name: koji zabbix checks
    job: /usr/lib/zabbix/kojihub-monitoring-checks
    minute: "*/2"
  when: 
    - zabbix_api_srv is defined
    - zabbix_monitoring
  tags:
    - monitoring

- block:
    - name: Distribute kojihub TLS validity check script
      ansible.builtin.template:
        src: kojihub-tls-check.j2
        dest: /usr/libexec/centos/kojihub-tls-check
        mode: '0750'
        owner: root
    - name: Reporting TLS validity value to zabbix
      ansible.builtin.cron:
        name: kojihub tls cert check
        job: /usr/libexec/centos/kojihub-tls-check
        minute: '*/30'
  when: koji_auth_tls
  tags:
    - monitoring    
