- name: Deploying enabled plugins
  copy:
    src: "plugins/{{ item }}.py"
    dest: "/usr/lib/koji-hub-plugins/{{ item }}.py"
    mode: 0755
  with_items: "{{ koji_hub_install_plugins }}"
  notify: 
    - restart_httpd
  tags:
    - plugins
 
- name: Configuring enabled plugins
  template:
    src: "koji-hub/plugins/{{ item }}.conf.j2"
    dest: "/etc/koji-hub/plugins/{{ item }}.conf"
    mode: 0644
  notify: restart_httpd  
  with_items: "{{ koji_hub_plugins_list }}"
  tags:
    - plugins

- block:
    - name: Importing fedora-messaging role
      include_role:
        name: fedora-messaging-client
      vars:
        fedora_messaging_tls_certs: True
        fedora_messaging_tls_cert: "{{ koji_hub_plugin_fedmsg_tls_cert }}"
        fedora_messaging_tls_key: "{{ koji_hub_plugin_fedmsg_tls_key }}"
        fedora_messaging_tls_ca: "{{ koji_hub_plugin_fedmsg_tls_ca }}"

    - name: Configuring fedora messaging
      template:
        src: koji-hub/plugins/fedora-messaging.toml.j2
        dest: /etc/fedora-messaging/config.toml
      notify: restart_httpd

    - name: Turning on boolean for fedora-messaging script/call
      seboolean:
        name: httpd_execmem
        persistent: yes
        state: yes

  when: "'fedmsg-koji-plugin' in koji_hub_plugins_list"
