- name: Ensuring we have some nfs pkgs installed
  yum:
    name: nfs-utils
    state: installed
 
- name: koji store mount point exist
  file:
    path: "{{ koji_mountpoint }}"
    state: directory

- name: Ensuring we have nfs koji store mounted
  mount:
    path: "{{ koji_mountpoint }}"
    src: "{{ koji_nfs_path }}"
    fstype: nfs
    state: mounted

- name: Ensuring we have a koji directory there
  file:
    path: "{{ koji_mountpoint }}/koji"
    state: directory
    owner: apache
    group: apache

- name: Workaround for some hard-coded path in koji
  file:
    src: "{{ koji_mountpoint }}/koji"
    dest: /mnt/koji
    state: link
  when: koji_mnt_symlink_workaround

- name: Ensuring we have default directories for koji storage
  file:
    path: "{{ koji_mountpoint }}/koji/{{ item }}"
    state: directory
    owner: apache
    group: apache
  with_items:
    - packages
    - repos
    - work
    - scratch

- block:
    - name: Additional koji volume[s] mount point[s] exist[s]
      file:
        path: "{{ item.dest }}"
        state: directory
        owner: apache
        group: apache
      with_items: "{{ koji_nfs_additional_mountpoints }}"

    - name: Ensuring addtional volume[s] is/are defined
      ansible.posix.mount:
        src: "{{ item.src }}"
        path: "{{ item.dest }}"
        fstype: nfs
        state: present
      register: additional_mountpoints  
      with_items: "{{ koji_nfs_additional_mountpoints }}"  
      loop_control:
        label: "{{ item.dest }}"
      tags:
        - nfs

    - name: Ensuring addtional volume[s] is/are mounted
      ansible.posix.mount:
        src: "{{ item.item.src }}"
        path: "{{ item.item.dest }}"
        fstype: nfs
        state: mounted  
      with_items: "{{ additional_mountpoints.results }}"
      when: item.changed
      loop_control:
        label: "{{ item.item.dest }}"
      tags:
        - nfs

    - name: Ensuring some default directories for additional volume[s]
      file:
        path: "{{ item.0.dest }}/{{ item.1 }}"
        state: directory
        owner: apache
        group: apache
      with_nested:  
        - "{{ koji_nfs_additional_mountpoints }}"
        - ['packages', 'repos', 'repos-dist', 'work', 'scratch' ]
      loop_control:
        label: "{{ item.0.dest }}/{{ item.1 }}"
      tags:
        - nfs
  when:
    - koji_nfs_mount
    - koji_nfs_mount_multi


- block:
    - name: Distributing pruning jobs script
      template:
        src: koji-prune-jobs.j2
        dest: /usr/libexec/centos/koji-prune-jobs
        owner: root
        mode: '0755'
    - name: Scheduling pruning jobs script 
      cron:
        name: "Koji scratch jobs cleanup"
        job: /usr/libexec/centos/koji-prune-jobs
        minute: "40"
        hour: "3"
 
  when: koji_prune_scratch_jobs
  tags:
    - pruning
