- block:
    - name: Specific PKI dir for koji
      ansible.builtin.file:
        path: /etc/pki/koji
        state: directory

    - name: Distributing some x509 files for kojihub
      copy:
        src: "{{ pkistore }}/{{ item }}"
        dest: "/etc/pki/koji/{{ item }}"
        mode: 0644
      with_items:
        - "{{ koji_hub_cacert }}"
        - "{{ koji_hub_tls_key }}"
        - "{{ koji_hub_tls_cert }}"
      notify:
        - restart_httpd
      when: koji_auth_tls

    - name: TLS certs for kojiweb
      copy:
        src: "{{ pkistore }}/{{ item }}"
        dest: "/etc/pki/tls/certs/{{ item }}"
        mode: 0644
      with_items:
        - "{{ koji_web_tls_cert }}"
        - "{{ koji_web_cacert }}"
      notify:
        - restart_httpd
        - restart_kojira

    - name: TLS keys for kojiweb
      copy:
        src: "{{ pkistore }}/{{ item }}"
        dest: "/etc/pki/tls/private/{{ item }}"
        mode: 0644
      with_items:
        - "{{ koji_web_tls_key }}"
      notify:
        - restart_httpd

    - name: Ensuring we have initial crl 
      ansible.builtin.get_url:
        url: "{{ koji_hub_tls_crl_url }}"
        dest: /etc/pki/koji/crl.pem
      when: koji_auth_tls
      register: new_crl
    
    - name: Verify if we need to convert CRL
      shell: 
        chdir: /etc/pki/koji
        cmd: openssl crl -in crl.pem -text >/dev/null 2>&1 || openssl crl -inform DER -in crl.pem -outform PEM -out crl.pem
      when: new_crl is changed 
  tags:
    - tls
    - pki
