# This task will allow koji to grab users from FAS/ACO and grant/remove build rights based on group membership

- name: Installing required python pkgs
  yum:
    name: "{{ kojihub_users_sync_pkgs }}"
    state: installed

- name: Ensuring we have a dir for bsadmin tool
  file:
    path: /etc/bsadmin
    state: directory
    owner: "{{ koji_admin_user }}"
    mode: 0750

- name: Configuring sync tool
  template:
    src: bsadmin.conf.j2
    dest: /etc/bsadmin/bsadmin.conf
    mode: 0644

- name: Distributing needed keytab
  copy:
    src: "{{ pkistore }}/krb5/{{ koji_fasjson_keytab }}"
    dest: "/etc/bsadmin/{{ koji_fasjson_keytab }}"
    mode: '0400'
    owner: "{{ koji_admin_user }}"
    group: "{{ koji_admin_user }}"
  when: koji_fasjson_sync

- name: Cron job to sync FAS/Koji
  cron:
    name: "CentOS ACO-koji sync"
    job: "/opt/cbs-tools/scripts/cbs-fas-sync.sh > /dev/null 2>&1"
    minute: "*/7"
    user: "{{ koji_admin_user }}"
  when: koji_fas_sync or koji_fasjson_sync  
