#!/bin/bash

# First the epel repositories
rsync_host="download-cc-rdu01.fedoraproject.org"
rsync_module="fedora-epel"
local_mirror_basedir="/mnt/koji/repos/epel"

for repo_path in 7 8/Everything next/8/Everything 9/Everything next/9/Everything; do
  for arch in x86_64 ppc64le aarch64 ; do
    test -d ${local_mirror_basedir}/${repo_path}/${arch}/Packages/ || mkdir -p ${local_mirror_basedir}/${repo_path}/${arch}/Packages/
    rsync ${rsync_host}::${rsync_module}/${repo_path}/${arch}/Packages/ ${local_mirror_basedir}/${repo_path}/${arch}/Packages/ -aH 2>&1 >/dev/null 
    pushd ${local_mirror_basedir}/${repo_path}/${arch} >/dev/null
    createrepo_c -d --update --retain-old-md 2 --workers=8 ./ 2>&1 >/dev/null
    popd >/dev/null
  done
done

# Now CentOS Stream 9 buildroots
download_dir="/mnt/kojishare/koji/repos/c9s-buildroot/"

for arch in x86_64 ppc64le aarch64; do 
  reposync --quiet --repofrompath=${arch},"https://kojihub.stream.centos.org/kojifiles/repos/c9s-build/latest/${arch}/" --repoid=${arch} --downloaddir=${download_dir} --download-metadata  >/dev/null 2>&1
  chown --quiet -R 755 ${download_dir}/${arch}
done

