#!/usr/bin/python3
import sys
import requests
import json
import os
from requests_gssapi import HTTPSPNEGOAuth
import logging
logging.basicConfig(level=logging.INFO, filename='/var/tmp/fasjson-groups-fetch.log', filemode='a', format='%(asctime)s - %(message)s')


fasjson_base_url = "{{ koji_fasjson_url }}"
fasjson_keytab = "{{ koji_fasjson_keytab }}"
fasjson_full_url = '%s/v1/groups/' % (fasjson_base_url)
os.environ['KRB5_CLIENT_KTNAME'] = '/etc/bsadmin/{{ koji_fasjson_keytab }}'
local_group_file = '/etc/bsadmin/groups'

if __name__ == '__main__':

  try:
    logging.info('[START] => Querying %s', fasjson_base_url)
    gssapi_auth = HTTPSPNEGOAuth(opportunistic_auth=True,mutual_authentication='OPTIONAL')
    results = requests.get(fasjson_full_url, auth=gssapi_auth) 
    json_body = json.loads(results.text)
    fo = open(local_group_file,"w")
    for group in json_body['result']:
      if group['groupname'].startswith('sig-'):
        logging.info('Querying [%s] for members of group [%s]', fasjson_base_url, group['groupname'])
        group_members_url = '%s/v1/groups/%s/members/' % (fasjson_base_url, group['groupname'])
        group_members = requests.get(group_members_url, auth=gssapi_auth)
        group_members_json = json.loads(group_members.text)
        userlist = []
        for user in group_members_json['result']:
          userlist.append(user['username'])
        string = '%s:%s \n' % (group['groupname'].replace('sig-','') , ','.join(userlist))
        fo.write (string)
    fo.close()

  except Exception as e:
    logging.error("Error occured see traceback", exc_info=True)
    sys.exit(1)

